package usecase

// This file was generated by the goro tool.

type Repository interface {
	SaveURL(string, string) (int64, error)
	GetURL(string) (string, error)
	// TODO: define interface to inject a service
}

type UseCase struct {
	repo Repository
}

func NewUseCase(r Repository) *UseCase {
	return &UseCase{
		repo: r,
	}
}
